# encoding: utf-8
context:
  encoding: utf-8
  script_name: my_script
  project_name: "My Python Project"
  author_name: "John Doe"
path_config:
  rename: project
  contents:
    my_script:
      rename: "{{{script_name}}}"
      executable: True
    pylib:
      rename: "pylib_{{{script_name}}}"
      contents:

